### ISSUE TITLE
acknowledged status

### ISSUE THREAD

**Issue by howardtopher** [ErikWegner/imoin#10]
Is it possible to query if a problem has been acknowledged?  And also for the icon in the toolbar, if a service problem has been acknowledged not include it in the count/status?  Basically, I think it would be beneficial to at least make it a user configurable option so that the toolbar icon only shows unacknowledged problems, but clicking the icon shows them all.

**Comment by ErikWegner** [comment]
It is definitely possible to differentiate acknowledged problems. There are some questions I would like to answer first, to get to a decent result from that change.

1. What is the purpose of the figure displayed on the toolbar icon? For me, it is the number of things (services and hosts) that are not OK. To acknowledge a service problem does not take away that problem, it does disable alerts from the monitoring system. To me personally, I still want to see that a problem exists.
2. To come around the first point, you already suggest an option to control the behaviour. In a first iteration it would be a global option (valid for all configured instances). Do you have a proposal for its caption?
3. Would a second option be required to also filter the list of problems in the pop-up? How should the list reflect acknowledged service problems?
4. Again for the icon in the toolbar, should it be green when there are only acknowledged failures? Should it have red and yellow background but lighter (maybe more transparent)?

**Comment by howardtopher** [comment]
All good questions. I'm sure you could ask a bunch of people and get all different answers, but for me:

1. If I've acknowledged a problem I now know it's there and would like to see it removed from the icon.  If it's not a critical problem that can wait, it could sit there for a while.  This way the icon becomes an indicator that something new has happened.  With all problems still in the list in the pop up, I can still be aware that there are still problems to fix.
2. Maybe something like "Don't include acknowledged problems in the toolbar icon status".
3. There could be a second option to filter the list in the pop up.  I had not considered that.  They could either not be shown, or collapsed down where you click a button to expand them.  Another idea is to put an icon next to the the acknowledged ones, much like nagios does in it's problem list, but this would not require a second option unless you want to give the user the ability to show/hide the icon.
4. I would go with green if all problems have been acknowledged, but that's just my personal preference.  This could also be configurable by the user to pick among different color schemes.

Thanks for your consideration of this idea.  If you decide to not do any of these, it's ok by me.  I'm still going to use the extension as I no longer have to keep a nagios tab open all the time!

**Comment by fleish** [comment]
@ErikWegner I'd like to add my voice to this request and perhaps take it a step further. My old Firefox add-on for this function offered numerous options for filtering things from showing up in the heads-up display. It had options to filter things based on regexp for hosts or services, hosts or services whose alarms had notifications disabled, hosts or services whose alarms had already been acknowledged. Would these types of things be possible to add to your extension?

**Comment by ErikWegner** [comment]
@fleish Thank you for these suggestions. Can you create a list of configuration options that you would like to see? Because you talk about filtering, I think of three point where filtering might happen:

* Query the backend (e.g. Nagios) with a filter query. This reduces the amount of data to be processed in the browser, but not every query might be possible with all backends. Using hostgroups/servicegroups might be one option.
* Filter the response during data processing in the add-on. This could work better across all backends. A regex would suite here.
* Filter in the popup. This might be the slowest option but could offer an on-the-fly-filtering.

When you bring up that list, maybe you can already propose which of the above option should be used for the implementation.

**Comment by fleish** [comment]
@ErikWegner I can definitely do that. First off, let me thank you for creating this addon since the one I've been using for years (https://addons.mozilla.org/en-US/firefox/addon/nagios-checker/) was abandoned and is now about to become obsolete due to the Firefox 57 overhaul & final nail in the coffin for the status bar (by way of the status-bar-4-evar add-on). Most/all of what I'm looking for in your add-on is already implemented in the above add-on, so if it's possible for you to review that code and glean ways to do things in your add-on that would be great. But regardless, I'll try to put things into words & screenshots. Would you prefer I continue this here or open a dedicated issue?

**Comment by ErikWegner** [comment]
Please open a new issue. Or, if you can cluster the new various new funtions, I could be helpful to have an issue for each cluster.

**Comment by ErikWegner** [comment]
#14 has details to enhance filtering.
